#!/usr/bin/perl
use warnings;
use strict;
use v5.10;
use autodie;

use Filesys::Statvfs;
use POSIX qw(strftime);

my ($dir, $free_pct) = @ARGV;

chdir $dir;

my $today = strftime("%Y-%m-%d", localtime);
my $logdir = "$ENV{HOME}/tmp/keepfree";
mkdir $logdir unless -d $logdir;
open STDOUT, ">>", "$logdir/$today";

for (;;) {
    my ($bsize, $frsize, $blocks, $bfree, $bavail,
        $files, $ffree, $favail, $flag, $namemax) = statvfs(".");

    last if $bavail * 100 / $blocks > $free_pct;
    opendir(my $dh, $dir);
    my @files = readdir($dh);
    @files = grep -f $_, @files;
    @files = sort { -M $b <=> -M $a } @files;
    printf("%s %.2f %s\n",
           strftime("%Y-%m-%dT%H:%M:%S%z", localtime),
           $bavail * 100 / $blocks, $files[0]);
    unlink $files[0];
}
